spring:
  data:
    cassandra:
      keyspace-name: spring_cloud
      port: 9042
      contact-points: localhost
  jackson:
    deserialization:
      read-unknown-enum-values-using-default-value: true
      fail-on-numbers-for-enums: true
      fail-on-unknown-properties: true
info:
  app:
    name: student-microservice
    description: Student Service
    version: v1.0
endpoints:
  actuator:
    enabled: true
    sensitive: true
  health:
    enabled: true
    sensitive: true
  metrics:
    enabled: true
    id: metrics
    sensitive: true
management:
  security:
    enabled: false